name: VietFruitZ
favicon: null
layout_spectrum: 0.26311
typography_spectrum: 0.74366
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131017'
    - '#fefefe'
    - '#ff9503'
    - '#ff4641'
    - '#1bcf7d'
  brandStrength: 0.25
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
